### ISSUE TITLE
bazel integration testing doesn't work with RBE

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel-integration-testing#90]
Due to the extraction optimization we do in the repository rule Bazel can't run on RBE.
I've worked around many of the parts by manipulating the mtime but there are more files needed (for example `$INSTALL_BASE/_embedded_binaries/embedded_tools/platforms/BUILD`).
I've experimented with using @damienmg's original unpacked version and it works on RBE.
We pay a cost of re-extracting bazel every test run which is currently ~10 seconds.
This is significant locally but trivial on CI given we can now parallelize (when one uses RBE the build server agents themselves are often weak and can't run many concurrent e2es) and cache hits.
Given the [work](https://docs.google.com/document/d/1Igmv-2GfXkoVFWTXvBYPeniQom8nLAwzqzridDlBIS4/edit?usp=sharing) in bazel on decreasing the binary size and decreasing extraction time it's reasonable to assume sometime in the next 6 months this cost will drop to 3-5 seconds.

@damienmg I want to remove the pre-extraction and just use the original bazel.
WDYT?

**Comment by damienmg** [comment]
There is an alternative option to extract that install base in a rule that
will then be used by actions. I believe at the moment we do it in a
repository rule because there were no tree artifacts at the time. This
would keep saving the extract time from the final test with staying
compatible with remote build.
